### ISSUE TITLE
`got` is unreliable for making requests

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/npm-name#12]
It randomly fails without even returning an `err.statusCode`.

```
λ ~/Public/npm-check/ node test                                                                                                                          ∞
err.statusCode undefined
{ RequestError
    at ClientRequest.req.once.err (/Users/niftylettuce/Public/npm-check/node_modules/got/index.js:73:21)
    at Object.onceWrapper (events.js:312:19)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'ENOTFOUND',
  message: 'getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:80',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'HEAD',
  path: '/foo' }
```

**Comment by niftylettuce** [comment]
irrelevant...
